spring:
  application:
    name: artemis
  profiles:
    active: dev
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${SUPABASE_JWK_SET_URI:https://jykhntdyjvirbinznxgv.supabase.co/auth/v1/.well-known/jwks.json}
  data:
    redis:
      repositories:
        enabled: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics

security:
  jwt:
    secret-key: ${JWT_SECRET:3cfa76ef14937c1c0ea519f8fc057a80fcd04a714f2a0c502d03433810c68f13}
    expiration: ${JWT_EXPIRATION:900000} # 15 minutes in ms
    refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 days in ms
