server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:aws-0-ap-northeast-1.pooler.supabase.com}:${DB_PORT:5432}/${POSTGRES_DB:postgres}?sslmode=require
    username: ${POSTGRES_USER:postgres.jykhntdyjvirbinznxgv}
    password: ${POSTGRES_PASSWORD:!StrongPassword!123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

logging:
  level:
    org.springframework: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: DEBUG

security:
  jwt:
    secret-key: ${JWT_SECRET:3cfa76ef14937c1c0ea519f8fc057a80fcd04a714f2a0c502d03433810c68f13}
    expiration: ${JWT_EXPIRATION:900000} # 15 minutes in ms
    refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 days in ms
